### ISSUE TITLE
concat : confusing hints 

### ISSUE THREAD

**Issue by roelof1967** [substack/stream-adventure#102]
Hello, 

If I read the hints and the example it looks like I need to use a http-server. 
But if I look at the solution I do not need it. 

I find this very confusing in learning  how to solve this .

Roelof

**Comment by anupamkumar** [comment]
you don't need to use http-server for that exercise. 

the example was just showing how to concatenate data coming in from a stream into a buffer. in that example HTTP POST data was coming in through the request (which is infact a stream in Node and so is response). And then do something with it and write a response based on incoming data.

**Comment by roelof1967** [comment]
Oke, thanks for the explanation
