### ISSUE TITLE
http_server checking error code

### ISSUE THREAD

**Issue by njeirath** [substack/stream-adventure#119]
I was walking through the http_server exercise and it was failing which I was able to trace down to the change made in 5a6c93dfa8fcbd369eba04730dfba1d7e50bfe7c on line 31 of index.js.  It appears this is sending the SIGTERM signal to the process and then expecting the child process to return a 0 but it returns 143 without any modifications to the solution:

```
stream-adventure verify http_server.js 

TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
ok 2 should be equal
not ok 3 successful exit code
  ---
    operator: equal
    expected: 0
    actual:   143
    at: ChildProcess.<anonymous> (/usr/lib/node_modules/stream-adventure/problems/http_server/index.js:31:11)
  ...

1..3
# tests 3
# pass  2
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

I was able to get my solution to pass by adding:

```
process.on('SIGTERM', function() {
  process.exit(0)
})
```

Which I suspect is not necessarily in the spirit of this particular tutorial.  I noticed a few other places where a chunk of code like this exists:

```
    ps.once('exit', function (code) {
      if (code) process.exit(code)
    });
```

I'm wondering if that is what should be on this line as well?

**Comment by calvinmetcalf** [comment]
if you upgrade to version 0.12.0 of node or 1.4.2 of io.js the solution works, v0.10.36 it fails.  In general I thought sigterm was only supposed to return a non-zero exit code if it encountered an error shutting things down, so this could be a node error.

**Comment by wengzilla** [comment]
Having a similar issue...

**Comment by calvinmetcalf** [comment]
@wengzilla are you using node 10?

**Comment by njeirath** [comment]
yes, I'm on 0.10.36

**Comment by ddelrio1986** [comment]
I was also having this issue. I upgraded to node v0.12 and it now works just fine.

**Comment by davsket** [comment]
Yeah, as @ddelrio1986 says, updating to 0.12.0 fix it. Is it possible to solve it to support previous versions of node? all 0.10.* versions fail on this exercise.

**Comment by calvinmetcalf** [comment]
Yeah sorry will look into it tommorow and try to figure out what changed

**Comment by davsket** [comment]
Thank you! :D

**Comment by njeirath** [comment]
I concur, updating node fixed the issue for me as well

**Comment by substack** [comment]
The exit code isn't checked anymore in 4.0.2.
