### ISSUE TITLE
Why my solution for №5[Lines] problem don't working?

### ISSUE THREAD

**Issue by evsign** [substack/stream-adventure#147]
```javascript
var offset = 0;
var cnt = 0;
process.stdin.on('readable', function(){
	var buf = process.stdin.read();
	if(!buf){return;}

	for(;offset < buf.length; ++offset){
		if(buf[offset] === 0x0a){
			if(cnt%2){
				process.stdout.write(buf.slice(0,offset+1).toString().toUpperCase());
			} else {
				process.stdout.write(buf.slice(0,offset+1).toString());
			}
			cnt++;
			buf = buf.slice(offset+1);
			offset = 0;
			process.stdin.unshift(buf);
			return;
		}
	}
	process.stdin.unshift(buf);
		
});
```

![0c548f878b](https://cloud.githubusercontent.com/assets/7965780/8486638/992c9340-210e-11e5-9b67-2831196e891b.jpg)

Actually this solution is working itself, when i run it manually, but when i run it for verify this is don't work on second test.
Help please)
p.s. i want to figure it out without any external libraries)
![dmbr9j5tgbbemp](https://cloud.githubusercontent.com/assets/7965780/8486647/b0bec730-210e-11e5-97d7-fa8abe349c60.jpg)

**Comment by evsign** [comment]
Sorry. I just forgot to use toLowerCase() ))

**Comment by BavarianBob** [comment]
Do you have an extensive background of coding or just beginning to learn node? I'm asking this for reference because I'm trying to solve this problem but am just beginning to learn node and I would have never thought of this solution. @evsign

**Comment by evsign** [comment]
@BavarianBob sorry, but i don't completely understand about what you're asking, and why) I learn programming only near one year, if that is what are you want to know)
I'm edit code in start post for working solution.
