### ISSUE TITLE
[Transform] Code is not finishing, stuck!

### ISSUE THREAD

**Issue by BavarianBob** [substack/stream-adventure#150]
Here is my code.

```javascript
var through = require('through2');
var transform = through(write,end);

function write(buffer){
  this.push(buffer.toString().toUpperCase());
};

function end(){     
  this.push(null);
}

process.stdin.pipe(transform).pipe(process.stdout);

```
This is the output: 

Expected:
MARSHMAN\niSOLUS\nLUGAL-IRRA-KUSH\nCROOKED PERSON\n

Actual:

MARSHMAN\niSOLUS

ok 3 successful exit code

**Comment by BavarianBob** [comment]
```javascript
var fs = require('fs');
var through = require('through2');

var transform = through(write, end);

function write (buffer, encoding, callback) {
       this.push(buffer.toString().toUpperCase());
        callback();
}

function end() {
    this.push(null);
    callback();
}

process.stdin.pipe(transform).pipe(process.stdout); 

```

Here is my final solution and it's correct.

**Comment by PokimLee** [comment]
`  var fs = require('fs');
  var through = require('through2');

  var transform = through(write, end);

  function write (buffer, encoding, callback) {
         this.push(buffer.toString().toUpperCase());
          callback();
  }

  function end(done) {
      done();
  }

  process.stdin.pipe(transform).pipe(process.stdout); `

base on @BavarianBob 's code, I modified the **end()** function and it just work!

**Comment by Clasen00** [comment]
@BavarianBob Why you use Callback() function? What for?
