### ISSUE TITLE
[WEBSOCKETS] segmentation fault

### ISSUE THREAD

**Issue by fdaciuk** [substack/stream-adventure#154]
This just happens when used with node v4.

**Comment by julianduque** [comment]
@fdaciuk can you post the complete log output? I'll investigate

**Comment by fdaciuk** [comment]
@julianduque it is just this :(

Look:

![selection_145](https://cloud.githubusercontent.com/assets/487669/10063116/97fc85b6-6240-11e5-8110-547dd7a2a936.png)

If I change to v0.10, it works fine.

**Comment by julianduque** [comment]
@fdaciuk are you reinstalling stream-adventure also?

**Comment by julianduque** [comment]
```

**Comment by fdaciuk** [comment]
Now everything works fine! Thanks @julianduque! :dancer: :dancer: :sparkles:
