### ISSUE TITLE
How are you supposed to verify exercise #7 - http server?

### ISSUE THREAD

**Issue by dsheffield206** [substack/stream-adventure#156]
when i type ```stream-adventure verify nameOfMyServer.js``` i get the console.log that my server is up and running and then nothing... nada. no verification. are there different instructions for this particular problem? stream-adventure verify isn't working.

**Comment by rafaeleyng** [comment]
For me, it works. Are you sure you're calling `next()` inside your transform stream? Not calling `next()` would cause what you've described.

**Comment by dsheffield206** [comment]
that's it. i was invoking ```next()``` correctly. left off the ```()```.
