### ISSUE TITLE
'crypt' refers to a module, but solution requires that user *not* export a module

### ISSUE THREAD

**Issue by sbma44** [substack/stream-adventure#76]
The problems immediately preceding it all involve exporting a module. This one takes a turn and returns to the earlier nodeschool pattern of being a simple script that operates directly on stdin and stdout.

It might be that the request to have the student hardcode those specific streams should be enough of a clue that we aren't building a commonjs module, but the instructions specifically say "module". For me, at least, this was totally confusing and I had to figure out the solution by cheating and looking it up even though the code at the crux of the exercise was all correct.

**Comment by substack** [comment]
I'm not sure what it used to say, but the problem statement talks clearly about stdin and stdout:

```
Your module will be given a passphrase on `process.argv[2]` and 'aes256'
encrypted data will be written to stdin.

Simply decrypt the data and stream the result to process.stdout.
```
