### ISSUE TITLE
Stream-Adventure, Duplexer Challenge real project example?

### ISSUE THREAD

**Issue by MohammedFadin** [substack/stream-adventure#80]
Hey!

I finished the Duplexer challenge, however, I'm not sure when to use it in a real life projects.

So, it takes a readable stream process.stdin and a writeable process.stdout, and joins them as a readable/writeable stream, correct? can somebody give me a real project example to demonstrate the use of Duplex streams?

**Comment by substack** [comment]
For some real-world examples, just check out the dependents lists for duplexer and duplexer2:

https://www.npmjs.com/browse/depended/duplexer2

https://www.npmjs.com/browse/depended/duplexer
